version: '2'
services:
  power_plant-app:
    image: power_plant
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://power_plant-postgresql:5432/power_plant
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  power_plant-postgresql:
    extends:
      file: postgresql.yml
      service: power_plant-postgresql
