version: '2'
services:
  power_plant-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/power_plant/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=power_plant
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5440:5432
